### PR TITLE
Long option can now be 1 character short

### PR DESCRIPTION
**Pull request by JanMikes**

### CODE REVIEW

**Comment by JanMikes** [comment]
I am not sure whether you want to cover this specific case with a test as it did not exist so far.

**Comment by tflori** [comment]
I've no idea whats wrong with hhvm....

**Comment by JanMikes** [comment]
> When a short option and a long option is named a which data does it receive? Or do we fail because there exists already a short or long option?

Well, depends if user will call command with `-a` or `--a`, not?

> I just saw that it was forbidden in version 1 already and got fixed in version 1.4.1

Ah I see, unfortunately for us, we were migrating from 1.1 where it was still allowed 😄 

> I know somewhere is a test that checks that an option identifier has to be unique. Might be a good point to start adding a test that there is also no short option with that name (at least if the long option has only one character).

Good, so expected behavior is to not allow `a` for both short and long options and throw exception in that case? I am able to cover/implement that.

**Comment by JanMikes** [comment]
HHVM is no longer supported: https://github.com/composer/composer/issues/8127

**Comment by tflori** [comment]
you can remove hhvm from travis config then...

**Comment by tflori** [comment]
@JanMikes any news on this topic?

**Comment by JanMikes** [comment]
Hello! I am sorry i was on holidays and had a break, will get back to this asap! Thank you for your patience, i definitely want this one get solved 😉 👍

**Comment by JanMikes** [comment]
I am not sure what to do with `OptionParser::completeOptionArray()`, specificly about this: `If either the short or the long option string is left out, the first element of the given array is interpreted   as either short (if it has length 1) or long`

Shal we keep this behavior and do not change it?

My opinion is yes, keep this and change it only when user on purpose wants 1 char long option, as this will not introduce BC break.

What do you think @tflori ?

**Comment by JanMikes** [comment]
Covered these cases with tests, throwing `InvalidArgumentException`.

I do not plan more changes unsless you want to.

**Pull request merged**
