### PR TITLE
test: update tests and config for PHPUnit 9.5.x

### PR DESCRIPTION
**Pull request by claylo**
All tests run now with PHPUnit 9.5.18 + text report of code coverage (tested with ext-pcov).

### CODE REVIEW

**Comment by tflori** [comment]
I would like to merge this but I'm afraid it will fail with php7.1 because phpunit 9.5 is not compatible. but compatibility with php8 is definitely a thing...

Do we need so many changes? can we not just add it to the composer.json?

**Comment by claylo** [comment]
Hi Thomas,

Since PHPUnit 9 is only a requirement for running the tests, I don't believe there's a need to change the PHP 7.1 requirement. I updated composer.json to allow installation of PHPUnit 9 ... not only with the PHPUnit version itself, but also the "PHP" requirement of `>=7.1 || ^8.0`.

I updated the `: void` returns for your tests using php-cs-fixer (as suggested [here](https://thephp.cc/articles/help-my-tests-stopped-working)), and made only two other substantive changes to `GetOpt\Test\Printer` (New inheritance from`PHPUnit\TextUI\DefaultResultPrinter`), changed 3 instances of `formatWithColor` to `colorizeTextBox` in `GetOpt\Test\Printer` (a PHPUnit 8 change, I believe), and one change in `GetOpt\Test\OptionParserTest` from `assertInternalType` to `assertArray`. 

No functional changes were made to anything -- this was all just so I could run the test suite with PHPUnit 9 and PHP 8. :)

**Comment by tflori** [comment]
I've merged your changes to a branch on this repo so that CI get's executed: https://gitlab.com/thflori/getopt-php/-/pipelines/490096079

As you can see the tests are now not working in php 7.1 and 7.2 because of the php requirement from phpunit. 

I additionally removed the custom printer, selected any phpunit and added a printer that works in all phpunit versions:
https://github.com/getopt-php/getopt-php/commit/e9eb44baa41a95a13efb7dd67aaf29cec2f88a5c

Unfortunately there is an issue with limedeck/phpunit-detailed printer - so that this also fails on php 7.1 and php 7.2:
https://github.com/LimeDeck/phpunit-detailed-printer/issues/23

**Comment by tflori** [comment]
I added another commit that installs the correct version per php version:
https://github.com/getopt-php/getopt-php/commit/90405946b4cf7c2fd356f74bc561c96311a731a3

Thanks for your contribution. FYI: I will close this one in favor of https://github.com/getopt-php/getopt-php/pull/176

**Pull request closed without merging**
