### PR TITLE
use magic getter for easier access to attributes

### PR DESCRIPTION
**Pull request by tflori**
replaces #99

### CODE REVIEW

**Comment by tflori** [comment]
@Bilge with this you get your getters, legacy code still works and I get my attributes. fine?

**Comment by Bilge** [comment]
I definitely wouldn't allow it if this was my library, but since it isn't, yes this is fine 👍

**Comment by Bilge** [comment]
Can we get a tag for this?

**Comment by Bilge** [comment]
@tflori In light of these deprecations don't you think the documentation should be updated?

**Comment by tflori** [comment]
yes, I guess that makes sense.

for the tag I want to resolve the conflicts in the help branch and merge this too before.

**Pull request merged**
