### PR TITLE
Changed Command API to use 'get' verb for accessor methods

### PR DESCRIPTION
**Pull request by Bilge**
For the next major release, because method names should [always start with a verb](http://codelegance.com/semantic-method-naming/). There may be other classes in need of similar refactoring but this seemed like a good place to start.

### CODE REVIEW

**Comment by tflori** [comment]
you are right and I don't know why I changed it (also in other classes). But I also don't like for every property to call a getter... so maybe to add also a magic getter and readd the current getters with `@deprecated` and `@codeCoverageIgnore` (if not already there) then we can also have this in version 3.1

**Comment by Bilge** [comment]
>I also don't like for every property to call a getter

That's the encapsulation pattern. If you don't like it you might as well just make all the encapsulated fields public instead of private, but I implore you not to do that.

>maybe to add also a magic getter

I implore you not to do that either. Almost every major project that began using magic methods since reverted because they're unclear, hard to debug, hard to extend, and apparently they're slow to resolve as well. Again, it would be better to just make the fields public rather than defer to magic methods if you don't see the point in encapsulation. 

I can understand why it's hard to see the point of encapsulating fields since 95% of the time they do nothing but call the backing field they encapsulate, but they afford us the flexibility to do stuff later, in a backwards-compatible manner. If the field is made public the object is not aware its fields are being manipulated, but by implementing the ubiquitous encapsulation pattern, we can respond to the events and do things like logging or implement lazy-loading of object internals.

I still think the way I've implemented this is correct and should target version 4.

**Comment by tflori** [comment]
You, know the magic getter is the only way to have a readonly property? Thats one of the main goals of encapsulation: not to be able to write properties from other objects. So you are absolutely right: we don't want public properties.

Too often since php 5 I see this in classes and I hate to write it and to use it:

```php
class Foo {
  protected $bar;
  public setBar($bar) { $this->bar = $bar; };
  public getBar($bar) { return $this->bar; };
}
```

While you set it once you use it often and you don't want to write everytime `getBar()`. So you create a temporary variable when you use it from the same context..

Of course, the IDE supports you (creates getters and setters, type hints, autocompletion etc.) but why? The point with the verb for method names: on one side I agree; on the other not. The verb should say what the class is doing (processing, reading, getting?) but it does not get anything with this getters. It already has this variable. It returns this variable - should it then be `returnBar()`? It's a naming convention accepted by the most - I don't fight against it but I don't absolutely agree.

As I said: we can change the method names to `get*()` again but there are three things needed to be changed for this PR. 

1. I want a phase where both names are working. From version 3.1 to 4 maybe or from version 4 to 5. In this phase the others should be marked as deprecated.
2. I want to keep the simplicity of accessing a property. There can be both: a direct getter and a magic one. You argue about the performance of magic getters: 0.07 seconds for 1 million calls - this is not an argument for me and if you care so much about it: you can still use the direct getters.
3. Consistency: when chaning the api of `Command` we should also change the the api of `Argument`, `Operand` and `Option`.

**Comment by Bilge** [comment]
1. Why do you want two APIs for the same thing? This is a generally a bad idea because if you provide *n* ways of doing the same thing, users need to override *n* implementations to provide a consistent API.
2. Again, why do you want to use a magic methods *and* a getter? You will have less BC breaks and less maintenance burden if you stick to one canonical way of doing the same thing.
3. That's fine, as stated in the PR description, this was just a starting point to see if this is something you want to pursue. We can fix the other classes once we have agreement on the direction to go in.

**Comment by tflori** [comment]
1. It's not two APIs it's two methods for the same thing while one is deprecated. Why to have deprecated code? Is this your question? So developers can adept there code to the new API or stop updating while they are still using deprecated code. It's a common way in programming.
2. Because many people don't care about ~0.00000007 seconds per call and more about readability. At least I do and in my eyes `$command->handler` is more readable than `$command->getHandler()`.

**Comment by Bilge** [comment]
A magic method implementation is a poor solution because if I just want to override `getFoo` I have to first realize a magic method is handling this case, then I have to override that magic method and be extra careful about handling only the *foo* case and not affecting all the other methods that are being routed through my implementation. The more cases I override, the more bloated and convoluted the magic method becomes. Contrast this to having a separate method for each getter, which keeps each concern clean and separate.

Furthermore, as you already mentioned, magic methods break static analysis, which doesn't just break IDE auto-completion but also code quality and style integrations, and anything else that relies on static analysis.

**Comment by tflori** [comment]
you are so complicated:

```php

class Foo {
  protected $bar;
  public function setBar($bar) { $this->bar = $bar; }
  public function getBar($bar) { return $this->bar; }
  public function __get($name) {
    switch ($name) {
      case 'bar': return $this->getBar();
      default: return null;
    }
  }
}
```

I'm guessing you interpret to much magic in the name magic getter :smiley:

**Comment by Bilge** [comment]
As stated, I don't think it's a good idea, but it's your project.

However, can you explain why you think this is more readable?
>in my eyes `$command->handler` is more readable than `$command->getHandler()`

**Comment by tflori** [comment]
because the handler is an attribute of command. It's just wrapped in a getter to have it readonly (or at least to control the writes to this property with a setter).

also it is misleading to the assumption that the class gets something. I'm tired to explain.. in the same time I could have changed the method names, add deprecated aliases and magic getters - what I will do now.

**Comment by Bilge** [comment]
It is the calling class that gets something.

**Comment by Bilge** [comment]
@tflori Thanks for your work 😄 👍

**Pull request closed without merging**
