### PR TITLE
Added callable typehint to Command constructor

### PR DESCRIPTION
**Pull request by Bilge**

### CODE REVIEW

**Comment by tflori** [comment]
there should not be any restriction here. I use it very different myself. It's just a suggestion to give a callable here.

you can also write your code very different and I'm wondering if we should remove the handler from constructor or make it optional at least.

in [the example](http://getopt-php.github.io/getopt-php/example.html) we provide a public handle. and this could be the default handle method:

```php
namespace GetOpt;

class Command {
  public function handle(GetOpt $getOpt) {
    if (empty($this->handler)) {
      throw new \Exception('missing handler');
    }
    call_user_func($this->handler, $getOpt);
  }
}
```

This way we could always call `$getOpt->getCommand()->handle($getOpt)` and it is still just a suggestion. For example: I'm using a string `method@controller` as handler..

**Comment by Bilge** [comment]
I wonder if your `method@controller` use case couldn't be written better using a callback, though...

The benefit to standardizing this as a callback is that you could begin to eliminate some (and in the future, hopefully *all*) of the boilerplate code from the example in the documentation. That is, if the routing logic has the guarantee that executable code is registered to the Command, it can just execute it itself instead of merely returning the Command object and leaving it to the caller to figure out what to do with it.

**Comment by tflori** [comment]
nope. I don't ever plan to execute the handler from `process()`. It's similar with routing you have a result. What he want's to do with this result is his responsibility. To call it with the GetOpt object, or just the options and operands. Parse a string or return a runtime configuration in object or array style.. up to him. Similar to [FastRoute](https://github.com/nikic/FastRoute/blob/master/src/RouteCollector.php#L36) it could be everything that he things is maybe a good handler.

**Comment by Bilge** [comment]
OK, closing this.

**Pull request closed without merging**
